name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Salesforce CLI and sfdx-git-delta
        run: |
          npm install -g sfdx-cli
          sfdx plugins:install sfdx-git-delta

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx_auth.txt
          sfdx force:auth:sfdxurl:store -f sfdx_auth.txt --setalias CONFIGURE_CI --setdefaultusername

      - name: Generate metadata delta
        run: |
          mkdir -p .temp
          sfdx sgd:source:delta --to HEAD --from HEAD^ --output .temp --generate-delta --source force-app/

      - name: Deploy metadata on main
        if: github.ref == 'refs/heads/main'
        run: |
          sfdx force:source:deploy -x .temp/package/package.xml --targetusername CONFIGURE_CI --testlevel RunLocalTests
