name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Salesforce CLI and sfdx-git-delta
        run: |
          npm install -g @salesforce/cli
          sf plugins install sfdx-git-delta --force

      - name: Authentificate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx_auth.txt
          sf org login sfdx-url --sfdx-url-file sfdx_auth.txt --alias CONFIGURE_CI --set-default

      - name: Generate metadata delta
        run: |
          mkdir -p .temp
          sf sgd:source:delta --to HEAD --from HEAD^ --output .temp --generate-delta --source force-app/

      - name: Deploy metadata on main
        if: github.ref == 'refs/heads/main'
        run: |
          sf project deploy start --manifest .temp/package/package.xml --target-org CONFIGURE_CI --test-level RunLocalTests
